version: 2.1
orbs:
  docker: circleci/docker@2.4.0
  go: circleci/go@1.9.0

jobs:
  lint-dockerfile:
    executor: docker/docker
    steps:
      - checkout
      - docker/hadolint:
          dockerfiles: ./Dockerfile

  test-app:
    executor:
      name: go/default
      tag: "1.15"
    steps:
      - checkout
      - run:
          name: "test app"
          command: "go test -v -short --count=1 $(go list ./...)"

  build-app-karsajobs:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Docker build"
          command: "docker build -t ghcr.io/fiqrimaulanaar/karsajobs:latest ."

      - run:
          name: "Login github"
          command: "echo $CR_PAT | docker login ghcr.io -u fiqrimaulanaar --password-stdin"

      - run:
          name: "Docker push"
          command: "docker push ghcr.io/fiqrimaulanaar/karsajobs:latest"

workflows:
  build-push-image:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs
