name: "karsajobs-ci"

on:
  push:
    branches: ["karsajobs"]
  pull_request:
    branches: ["karsajobs"]

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
  test:
    needs: lint-dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Test app
        run: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    needs: [lint-dockerfile, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker build
        run: docker build -t ghcr.io/fiqrimaulanaar/karsajobs:latest .

      - name: Docker login
        run: docker login --username fiqrimaulanaar --password $ {{ secrets.PACKAGES_TOKEN }} ghcr.io

      - name: Docker push
        run: docker push ghcr.io/fiqrimaulanaar/karsajobs:latest
