name: "karsajobs-ui-ci"

on:
  push:
    branches: ["karsajobs-ui"]

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile

  build-app-karsajobs-ui:
    needs: lint-dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker build
        run: docker build -t ghcr.io/fiqrimaulanaar/karsajobs-ui:latest .

      - name: Docker login
        run: docker login --username fiqrimaulanaar --password ${{ secrets.PACKAGES_TOKEN }} ghcr.io

      - name: Docker push
        run: docker push ghcr.io/fiqrimaulanaar/karsajobs-ui:latest
